# Generated by Django 3.1.3 on 2022-05-08 20:04

from django.db import migrations, models
import homecam.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CapturePicture',
            fields=[
                ('cpid', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=homecam.models.user_directory_path)),
                ('time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'capture_picture',
                'managed': False,
            },
        ),
    ]
