# Generated by Django 3.1.3 on 2022-05-10 21:25

from django.db import migrations, models
import homecam.models


class Migration(migrations.Migration):

    dependencies = [
        ('homecam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordingVideo',
            fields=[
                ('rvid', models.AutoField(primary_key=True, serialize=False)),
                ('video', models.FileField(upload_to=homecam.models.user_directory_path_video_userRequest)),
                ('time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'recording_video',
                'managed': False,
            },
        ),
    ]
