# Generated by Django 3.1.3 on 2022-05-20 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homecam', '0003_detectperson'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectAnimal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('species', models.IntegerField(blank=True, null=True)),
                ('location', models.IntegerField(blank=True, null=True)),
                ('time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'detect_animal',
                'managed': False,
            },
        ),
    ]
