# Generated by Django 3.1.3 on 2022-05-31 07:57

from django.db import migrations, models
import homecam.models


class Migration(migrations.Migration):

    dependencies = [
        ('homecam', '0004_detectanimal'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecognitionFace',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image1', models.ImageField(upload_to=homecam.models.user_directory_path_recognition_face)),
                ('image2', models.ImageField(upload_to=homecam.models.user_directory_path_recognition_face)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('camid', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'recognition_face',
                'managed': False,
            },
        ),
    ]
