# Generated by Django 3.1.3 on 2022-06-10 08:51

from django.db import migrations, models
import homecam.models


class Migration(migrations.Migration):

    dependencies = [
        ('homecam', '0007_safemodenodetect'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectFalldown',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image1', models.ImageField(upload_to=homecam.models.user_directory_path_detect_falldown)),
                ('image2', models.ImageField(upload_to=homecam.models.user_directory_path_detect_falldown)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('camid', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'detect_falldown',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SafeModeNoaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image1', models.ImageField(upload_to=homecam.models.user_directory_path_safemode_noaction)),
                ('image2', models.ImageField(upload_to=homecam.models.user_directory_path_safemode_noaction)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('period', models.IntegerField(blank=True, null=True)),
                ('camid', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'safe_mode_noaction',
                'managed': False,
            },
        ),
    ]
