# Generated by Django 3.1.3 on 2022-06-14 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homecam', '0008_detectfalldown_safemodenoaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='CamConnectHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('camid', models.CharField(blank=True, max_length=45, null=True)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('division', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'cam_connect_history',
                'managed': False,
            },
        ),
    ]
