# Generated by Django 3.1.3 on 2022-06-15 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homecam', '0009_camconnecthistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomecamModeUseHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('camid', models.CharField(blank=True, max_length=45, null=True)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('mode', models.CharField(blank=True, max_length=45, null=True)),
                ('division', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'homecam_mode_use_history',
                'managed': False,
            },
        ),
    ]
