# Generated by Django 3.1.3 on 2022-06-29 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homecam', '0010_homecammodeusehistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DetectFalldown',
        ),
    ]
