# Generated by Django 3.1.3 on 2022-04-30 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('fid', models.AutoField(primary_key=True, serialize=False)),
                ('image1', models.ImageField(upload_to='images/family/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='images/family/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='images/family/')),
                ('name', models.CharField(max_length=150)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
                ('tel', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'db_table': 'family',
                'managed': False,
            },
        ),
    ]
