name: Docker Publish

on:
  push:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./SmartHomeCam
    steps:
      - uses: actions/checkout@v2

      - name: Docker build
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/image-name .

      - name: Docker Login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Push
        run: docker push ${{ secrets.DOCKER_USERNAME }}/image-name
